export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";

export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";

export const LOGIN_RESET = "LOGIN_RESET";

export const REFRESH_REQUEST = "REFRESH_REQUEST";
export const REFRESH_SUCCESS = "REFRESH_SUCCESS";
export const REFRESH_FAILED = "REFRESH_FAILED";

export const SET_NAME = "SET_NAME";
export const REMOVE_TO_CART = "REMOVE_TO_CART";

export const ADD_TO_CART_REQ = "ADD_TO_CART_REQ";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const ADD_TO_CART_FAILED = "ADD_TO_CART_FAILED";

export const GET_TO_CART_REQ = "GET_TO_CART_REQ";
export const GET_TO_CART_SUCCESS = "GET_TO_CART_SUCCESS";
export const GET_TO_CART_FAILED = "GET_TO_CART_FAILED";

export const REMOVE_TO_CART_REQ = "REMOVE_TO_CART_REQ";
export const REMOVE_TO_CART_SUCCESS = "REMOVE_TO_CART_SUCCESS";
export const REMOVE_TO_CART_FAILED = "REMOVE_TO_CART_FAILED";

export const LAND_REDIRECT = "LAND_REDIRECT";
export const LAND_REDIRECT_SUCCESS = "LAND_REDIRECT_SUCCESS";
export const LAND_REDIRECT_FAILED = "LAND_REDIRECT_FAILED";
